### ISSUE TITLE
Resetting a color

### ISSUE THREAD

**Issue by IonicaBizau** [jbnicolai/ansi-256-colors#2]
Is it possible to reset only the foreground color, instead of all styles?

I see there is the `colors.reset` thing that resets everything.

**Comment by jbnicolai** [comment]
@IonicaBizau I'm afraid that's not possible, due to the way terminal color escape sequences are implemented

**Comment by IonicaBizau** [comment]
@jbnicolai Actually, I found the solution and pushed [a fix in `couleurs`](https://github.com/IonicaBizau/couleurs/pull/7):

For resetting the color I use:

 - `u001b\[39m` [for foreground colors](https://github.com/IonicaBizau/couleurs/blob/429ec63b48597ab2d185be2e04c3294ad15a8ed6/lib/index.js#L75)


 - `\u001b[49m` for [background colors](https://github.com/IonicaBizau/couleurs/blob/429ec63b48597ab2d185be2e04c3294ad15a8ed6/lib/index.js#L97)

Thanks for feedback. :four_leaf_clover:
